import type { TLDInfo } from '../types.js';

export const TLD_DATABASE: Record<string, TLDInfo> = {
  com: {
    tld: 'com',
    description: 'Commercial - the most recognized TLD worldwide',
    typical_use: 'Businesses, commercial websites, general purpose',
    price_range: { min: 8.88, max: 15.99, currency: 'USD' },
    renewal_price_typical: 12.99,
    restrictions: [],
    popularity: 'high',
    category: 'generic',
  },
  io: {
    tld: 'io',
    description: 'British Indian Ocean Territory - popular with tech startups',
    typical_use: 'Tech startups, SaaS products, developer tools',
    price_range: { min: 29.88, max: 59.99, currency: 'USD' },
    renewal_price_typical: 44.99,
    restrictions: [],
    popularity: 'high',
    category: 'country',
  },
  dev: {
    tld: 'dev',
    description: 'Developer - for software developers and their projects',
    typical_use: 'Developer portfolios, tools, documentation sites',
    price_range: { min: 10.18, max: 19.99, currency: 'USD' },
    renewal_price_typical: 14.99,
    restrictions: ['Requires HTTPS (HSTS preloaded)'],
    popularity: 'medium',
    category: 'new',
  },
  app: {
    tld: 'app',
    description: 'Application - for mobile and web applications',
    typical_use: 'Mobile apps, web applications, software products',
    price_range: { min: 11.18, max: 19.99, currency: 'USD' },
    renewal_price_typical: 14.99,
    restrictions: ['Requires HTTPS (HSTS preloaded)'],
    popularity: 'medium',
    category: 'new',
  },
  co: {
    tld: 'co',
    description: 'Colombia / Company - popular alternative to .com',
    typical_use: 'Companies, startups, short URLs',
    price_range: { min: 9.48, max: 29.99, currency: 'USD' },
    renewal_price_typical: 24.99,
    restrictions: [],
    popularity: 'high',
    category: 'country',
  },
  net: {
    tld: 'net',
    description: 'Network - originally for network providers',
    typical_use: 'Technology companies, network services, ISPs',
    price_range: { min: 9.88, max: 14.99, currency: 'USD' },
    renewal_price_typical: 12.99,
    restrictions: [],
    popularity: 'high',
    category: 'generic',
  },
  org: {
    tld: 'org',
    description: 'Organization - for non-profits and communities',
    typical_use: 'Non-profit organizations, open source projects, communities',
    price_range: { min: 9.88, max: 14.99, currency: 'USD' },
    renewal_price_typical: 12.99,
    restrictions: [],
    popularity: 'high',
    category: 'generic',
  },
  ai: {
    tld: 'ai',
    description: 'Anguilla / Artificial Intelligence - trending for AI projects',
    typical_use: 'AI/ML projects, tech startups, research',
    price_range: { min: 49.88, max: 99.99, currency: 'USD' },
    renewal_price_typical: 79.99,
    restrictions: [],
    popularity: 'medium',
    category: 'country',
  },
  xyz: {
    tld: 'xyz',
    description: 'XYZ - for the next generation of internet users',
    typical_use: 'Creative projects, personal sites, unconventional brands',
    price_range: { min: 1.99, max: 12.99, currency: 'USD' },
    renewal_price_typical: 12.99,
    restrictions: [],
    popularity: 'medium',
    category: 'new',
  },
  me: {
    tld: 'me',
    description: 'Montenegro - popular for personal brands',
    typical_use: 'Personal websites, portfolios, URL shorteners',
    price_range: { min: 9.88, max: 19.99, currency: 'USD' },
    renewal_price_typical: 17.99,
    restrictions: [],
    popularity: 'medium',
    category: 'country',
  },
  sh: {
    tld: 'sh',
    description: 'Saint Helena - popular with developers (shell scripts)',
    typical_use: 'Developer tools, CLI applications, tech projects',
    price_range: { min: 29.88, max: 49.99, currency: 'USD' },
    renewal_price_typical: 44.99,
    restrictions: [],
    popularity: 'low',
    category: 'country',
  },
  bot: {
    tld: 'bot',
    description: 'BOT - for chatbots, automation products, and agent tooling',
    typical_use: 'AI agents, bots, automations, developer tooling',
    price_range: { min: 39.99, max: 89.99, currency: 'USD' },
    renewal_price_typical: 59.99,
    restrictions: [],
    popularity: 'medium',
    category: 'new',
  },
  cc: {
    tld: 'cc',
    description: 'Cocos Islands - often used as "Creative Commons"',
    typical_use: 'Creative projects, alternative to .com',
    price_range: { min: 9.88, max: 24.99, currency: 'USD' },
    renewal_price_typical: 19.99,
    restrictions: [],
    popularity: 'low',
    category: 'country',
  },
};

export function getTldCatalogEntry(tld: string): TLDInfo {
  const normalizedTld = tld.trim().toLowerCase();
  return TLD_DATABASE[normalizedTld] || {
    tld: normalizedTld,
    description: `${normalizedTld.toUpperCase()} domain extension`,
    typical_use: 'General purpose',
    price_range: { min: 10, max: 50, currency: 'USD' },
    renewal_price_typical: 20,
    restrictions: ['Check registrar for specific restrictions'],
    popularity: 'low',
    category: 'generic',
  };
}
